### ISSUE TITLE
Expose repositories search outside of the CLI tool

### ISSUE THREAD

**Issue by taktran** [Financial-Times/ebi#27]
Some ideas:

* Add a page to [houston](https://houston.ft.com/)
* [Octokit runs in the browser](https://github.com/octokit/rest.js#browser), so we could have a single page app or some sort too. Github pages?
* Chrome extension
* Slackbot

Some things to avoid

* Caching - having a database/state outside of github.com means we need to run and maintain it, and absorb all the issues that come with that

**Comment by quarterto** [comment]
would also allow using it for the transformation-runner interactive prompt

**Comment by taktran** [comment]
We could move the underlying github search logic into https://github.com/Financial-Times/tooling-helpers

**Comment by taktran** [comment]
Follow the lead with https://github.com/Financial-Times/manage-github-apps/issues/59, so we can use the underlying search logic as a library

Logic to go into: https://github.com/financial-times/github

**Comment by taktran** [comment]
This can be done after the v1.2.0 release, as we'll want https://github.com/Financial-Times/manage-github-apps/issues/59 and equivalent to be done first

**Comment by quarterto** [comment]
bump

**Comment by taktran** [comment]
@quarterto something like this, that maps to the command line commands?

```
const { contents, package } = require('ebi');
const repos = [
  'Financial-Times/nori',
  'Financial-Times/tako',
  'Financial-Times/ebi'
];

contents({
  filepath: 'package.json',
  search: 'snyk', // optional
  regex: /snyk/, // optional  
})(repos);

package({
  search: 'snyk', // optional
  regex: /snyk/, // optional  
})(repos)

package.engines({
  search: 'snyk', // optional
  regex: /snyk/, // optional  
})(repos)
```

Output would be the same as [`--json` output](https://github.com/Financial-Times/ebi#json-output) of the command line:

```
[
  {
    type,
    repository,
    filepath,
    fileContents,
    [search],
    [regex],
    [error]
  }
]
```

**Comment by quarterto** [comment]
that would be perfect! although i'm guessing it'd reject the promise instead of returning `error` in the response?

**Comment by taktran** [comment]
Good point about the `error`.

So sketching out how you would get search results, you would do something like:

```
// Can't just use Promise.all as it only resolves if all promises resolve, and fails if
// there is even one promise rejection

async function mapAll() {
  const findPromises = list
    .map(p => p.catch(() => undefined));
  const output = (await Promise.all(findPromises))
    .filter(p => p !== undefined);

  console.log('mapAll:', output);
}

const allSettled = require('promise.allsettled');
async function useAllSettled() {
  const output = await allSettled(list);
  const fulfilledOutput = output
    .filter(({ status }) => status === 'fulfilled')
    .map(({ value }) => value);
  const rejectedOutput = output
    .filter(({ status }) => status === 'rejected')
    .map(({ reason }) => reason);

  console.log('allSettled fulfilled:', fulfilledOutput);
  console.log('allSettled rejected:', rejectedOutput);
}
```

https://repl.it/@taktran/Promise-array
