### ISSUE TITLE
Better errors on invalid input

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/ebi#72]
If I pass in `https://github.com/Financial-Times/ebi` as input, we get back an error like so...

```
ERROR 404: 'https://github.com/Financial-Times/ebi' not found
```

Which is confusing. The input should have been `Financial-Times/ebi`, and the tool should tell us so.

**Comment by taktran** [comment]
Another alternative to throwing an error, is to just allow the various forms of github repos like here: https://github.com/Financial-Times/manage-github-apps/blob/master/src/lib/github.js#L40

(thanks to @simonplend for the shout out 😄)

**Comment by taktran** [comment]
Going to add support for different repo formats, so reopening this.
