### ISSUE TITLE
Pass in input as a list at the end of the arguments

### ISSUE THREAD

**Issue by taktran** [Financial-Times/ebi#75]
Add the repositories as variadic arguments at the end eg, <name>... in the following:

    naval_fate.py ship new <name>...

Inspiration: http://try.docopt.org/

Yargs allows it with https://github.com/yargs/yargs/blob/master/docs/advanced.md#variadic-positional-arguments

TODO:

* [x] First pass of getting arguments working + test
* [x] Add `withRepoList` to add description to help
* [x] Refactor tests to run tests for both stdin and arguments
* [x] Figure out why husky is broken
* [x] ~~Which should take precedence stdin or list arguments? Or both, or error if both?~~ Error if both stdin and arguments is provided
* [x] Add to `package` and `package:engines` command

## Old ideas

Can add  as `--file` `--repos` or equivalent

eg,

```
npx ebi --file repositories.txt package:engines
npx ebi --repos Financial-Times/ebi,Financial-Times/tako package:engines
npx ebi --org Financial-Times --repos ebi,tako package:engines
```

Might relate to https://github.com/Financial-Times/ebi/issues/7, for `--org` flag

**Comment by taktran** [comment]
TODO: What is the diff between `user` and `org` for GitHub?

**Comment by taktran** [comment]
Actually, I misinterpreted the initial feature request from @sjparkinson. What he meant was to add the repositories as arguments at the end eg, `<name>...` in the following:

    naval_fate.py ship new <name>...

Inspiration: http://try.docopt.org/

Yargs allows it with https://github.com/yargs/yargs/blob/master/docs/advanced.md#variadic-positional-arguments

**Comment by sjparkinson** [comment]
The only other command line tool I've seen do something like `--repos Financial-Times/ebi,Financial-Times/tako` was Ansible, and it felt very unintuitive.

```
$ ansible -i 10.0.0.1,10.0.0.2
$ ansible -i 10.0.0.1,
```

> https://docs.ansible.com/ansible/latest/cli/ansible.html#cmdoption-ansible-i

And yeah, you really had to include a comma if you only had one host to pass in 🤦‍♀️

**Comment by taktran** [comment]
Fixed with https://github.com/Financial-Times/ebi/pull/82
