### ISSUE TITLE
Implement version update prompt

### ISSUE THREAD

**Issue by jenniferemshepherd** [Financial-Times/ebi#89]
So that users know when `ebi` has been updated with further features, we would like there to be a command line prompt to upgrade (`npm i`) `ebi`.

**Comment by jenniferemshepherd** [comment]
as per [Github Tooling Helper ](https://github.com/Financial-Times/github/blob/master/bin/github.js#L58-L73)

**Comment by taktran** [comment]
And also this PR: https://github.com/Financial-Times/github/pull/41/
